development/controllers/SiteController.php
<?php

class SiteController extends Controller
{
	/**
	 * Defines the access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow',
				'actions'=>array('edit', 'resend', 'message'),
				'users'=>array('@'),
			),
			array('allow',
				'actions'=>array('index', 'list', 'login', 'logout', 'page', 'register', 
					'session', 'validate', 'confirm', 'report', 'approve', 'error', 
					'category', 'job', 'person', 'post', 'store', 'stats7'),
				'users'=>array('*'),
			),
		);
	}
	
	protected function accessDenied($user, $message)
	{
		throw new CHttpException(403, $message);
	}
	
	/**
	 * Declares class-based actions
	 */
	public function actions()
	{
		return array(
			'page'=>array(
				'class'=>'CViewAction',
			),
		);
	}

	/**
	 * This is the action to handle external exceptions
	 */
	public function actionError($code=null)
	{
		$error = app()->errorHandler->error;
    	if (app()->request->isAjaxRequest) {
    		echo $error['message'];
    	} else {
    		if ($error) {
    			$code = $error['code'] != 404 ? $error['code'] : false;
    			$login = $code == 403 && user()->isGuest;
    			$url = ($login ? 'login' : 'error'.($code ? "/$code" : ''));
    			$this->redirect($this->createUrl($url));
    		}
			$this->render('error', array('code'=>$code ? $code : 404));
		}
	}
	
	/**
	 * Display tasks in list view
	 */
	public function actionList($agent, $order=false, $model=null, $set=null)
	{
		if (app()->request->isAjaxRequest) {
			if ($set === null) {
				if ($order) updateRefine($agent, $order, $model);
				if ($order && $model == 'Category') {
					state('ajax', array('category', $order));
				} else if ($agent != Agent::Browse) {
					if (!user()->isGuest) {
						$action = $agent == Agent::Accounts ? 'account' : ($agent 
						== Agent::Profile ? 'profile' : 'space');
						state('ajax', array($action, null));
					} else {
						$agent = Agent::Browse;
					}
				} else {
					state('ajax', array('index', null));
				}
				state('agent', $agent);
			} else {
				$refine = state('refine');
				$refine[$set] = $order;
				state('refine', $refine);
			}
			$this->widget('application.components.ListView', array(
				'agent'=>$agent,
			));
		}
	}

	/**
	 * Authorize email login
	 */
	public function actionLogin()
	{
		$model = personModel();
		if (isset($_POST['Person'])) {
			$model->attributes = $_POST['Person'];
			if ($model->login()) {
				$this->redirect(app()->homeUrl.'#!/');
			} else {
				$model->password = '';
			}
		}
		$this->render('index', array('class'=>'auth', 'model'=>$model));
	}
	
	/**
	 * Complete logout and redirect
	 */
	public function actionLogout()
	{
		user()->logout();
		if ($logout = facebook_api('logout')) {
			$this->redirect($logout);
		} else {
			$this->redirect(app()->homeUrl.'#!/');
		}
	}
	
	/**
	 * Process email registration
	 */
	public function actionRegister($member='customer')
	{
		$model = isset($_POST['Hub']) ? registerProfile($_POST['Hub'], 
		$member) : hubModel();
		$this->render('index', array('class'=>'auth', 'model'=>$model));
	}
	
	/**
	 * Updates the session variable data
	 */
	public function actionSession()
	{
		ignore_user_abort(1);
		foreach ($_GET as $key=>$val) {
			state($key, $val);
		}
	}
	
	/**
	 * Validate unique person
	 */
	public function actionValidate()
	{
		if (app()->request->isAjaxRequest && isset($_GET['Person'])) {
			foreach ($_GET['Person'] as $name=>$value) {
				if (!Person::model()->count($name.'=:val AND locked = 0', 
				array(':val'=>$value))) {
					echo CJavaScript::jsonEncode(false);
					return;
				}
			}
			echo CJavaScript::jsonEncode(true);
		}
	}
	
	/**
	 * Confirm email received
	 */
	public function actionConfirm($state, $code)
	{
		list($out, $person) = confirmCode($state, $code);
		if ($out) {
			if ($out == 'validChange' || $out == 'validEmail') {
				if ($out == 'validChange') {
					$person->email = $person->new_email;
					$person->new_email = null;
				}
				$person->valid_email = 1;
				$person->save();
			} else if ($out == 'validReset') {
				$refine = state('refine');
				foreach (multiRefine() as $i=>$multi) {
					if ($multi['panel'] == 'Accounts') {
						$refine[$i] = 'security';
					}
				}
				state('refine', $refine);
				$this->redirect(app()->createUrl('my/account'));
			}
			state('name', $person ? $person->first_name : '');
			$this->redirect(app()->createUrl("mail/$out"));
		}
		$this->redirect(app()->homeUrl);
	}
	
	/**
	 * Report from email
	 */
	public function actionReport($entry)
	{
		list($out, $email, $person) = reportCode($entry, true);
		if ($out == 'oldEmail') {
			$person->email = $email;
			$person->confirm_key = $person->new_email = null;
			$person->save();
		} else if ($out == 'newPassword') {
			$person->password = null;
			$person->save();
			// send password reset link
		}
		state('email', $email);
		state('name', $person ? $person->first_name : '');
		$this->redirect(app()->createUrl("mail/$out"));
	}
	
	/**
	 * Resend verification link
	 */
	public function actionResend()
	{
		if (app()->request->isAjaxRequest && verify(1)) {
			$subject = array('Activate this email', 'Verify your account');
			$type = array('newEmail', 'verifyEmail');
			$i = user()->person->new_email ? 0 : 1;
			queueMail(array('confirm'=>confirmCode($type[$i])), $subject[$i], $type[$i]);
		}
	}
	
	/**
	 * Redirect for users
	 */
	private function renderRoute($data, $route, $flush=true)
	{
		$action = $this->action->id;
		$focus = array('data'=>$data, 'route'=>$route);
		state('ajax', array($action, $data));
		if ($route) {
			$url = $this->createUrl('site/index')."#!/$action".($data ? "/$data" : '');
			if ($flush) {
				echo pageHeader().'<script type="text/javascript">document.title = "'.
				title('Please wait').'"; window.location = "'.$url.'"</script>';
				echo strstr($this->render('index', $focus, true), '<meta name');
			} else {
				$this->redirect($url);
			}
		} else {
			$this->render('index', $focus);
		}
	}
	
	/**
	 * View store page
	 */
	public function actionStore($name, $login=false, $route=true, 
	$paid=false, $token=null, $PayerID=null)
	{
		if ($paid && $token) {
			ignore_user_abort(1);
			// display a payment.php page "Payment processing..."
			$result = paypal_nvp('get', $token);
			if ($result && $result['PAYERID'] == $PayerID && paypal_nvp('make', $result)) {
				$task = Task::model()->findByPk($result['task_id']);
				$payment = new Payment;
				$payment->task_id = $task->row_id;
				$payment->person_id = $task->person_id;
				$payment->amount = $result['amount'];
				$payment->commit = 1;
				$payment->paid_on = new CDbExpression('NOW()'); 
				foreach ($result['designs'] as $mirror) {
					$design = Design::model()->find('task_id=:tid AND mirror=:mirror', 
					array(':tid'=>$task->row_id, ':mirror'=>$mirror));
					if (!$design->sold) {
						$design->sold = 1;
						$design->save();
						$payment = new Payment;
						$payment->task_id = $task->row_id;
						$payment->person_id = $design->person_id;
						$payment->amount = $task->price;
						$payment->debit = 0;
						$payment->fee = paypal_fee($task->price);
						$payment->save();
						$subject = "Purchase Invoice #$mirror";
						queueMail(array('design_id'=>$design->row_id, 
						'task_id'=>$task->row_id), $subject, 'invoice');
					}
				}
				$this->renderRoute($name, $route, false);
			} else {
				$this->redirect($this->createUrl('site/error', array('code'=>503)));
			}
		} else if (match_like('Task', $name)) {
			if ($login && user()->isGuest) {
				state('ajax', array('store', $name));
				$this->redirect($this->createUrl('site/login'));
			}
			$this->renderRoute($name, $route);
		} else {
			$this->missingAction('');
		}
	}
	
	/**
	 * View register confirmation
	 */
	public function actionApprove()
	{
		$this->render('index', array('class'=>'register'));
	}
	
	/**
	 * Browse category
	 */
	public function actionCategory($name, $route=true)
	{
		$this->renderRoute($name, $route);
	}
	
	/**
	 * View job page
	 */
	public function actionJob($name, $route=true)
	{
		if (match_like('Task', $name)) {
			$this->renderRoute($name, $route);
		} else {
			$this->missingAction('');
		}
	}
	
	/**
	 * View design message
	 */
	public function actionMessage($name, $order)
	{
		$task = match_like('Task', $name);
		$design = $task ? Design::model()->find('task_id=:tid AND mirror'.
		'=:mirror', array(':tid'=>$task->row_id, ':mirror'=>$order)) : false;
		state('ajax', array('message', array($name, $order)));
		if ($design && ($task->person_id == user()->id || $design->person_id == 
		user()->id)) {
			header('Location: '.$this->createAbsoluteUrl("#!/message/$name/$order"));
		} else {
			$this->missingAction('');
		}
	}
	
	/**
	 * View user profile
	 */
	public function actionPerson($alias, $route=true)
	{
		if (match_like('person', $alias)) {
			$this->renderRoute($alias, $route);
		} else {
			$this->missingAction('');
		}
	}
	
	/**
	 * Post job brief
	 */
	public function actionPost($route=true)
	{
		$this->renderRoute(null, $route);
	}
	
	/**
	 * Stats for protopage feed
	 */
	public function actionStats7()
	{
		echo '<div style="font-family: arial; font-size: 10pt; text-align: center">';
		$fields = array('Technetium'=>array(Payment::model(), 'debit=1'), 'Customers'=>
			array(Person::model(), 'member="customer"'), 'Designs'=>Design::model());
		foreach ($fields as $desc=>$model) {
			$list = is_array($model) ? $model[0]->findAll($model[1]) : $model->findAll();
			echo "<p>$desc: ".count($list).'</p>';
		}
		echo '</div>';
	}
	
	/**
	 * Default action
	 */
	public function actionIndex()
	{
		if (isset($_GET['_escaped_fragment_'])) {
			header("HTTP/1.1 301 Moved Permanently");
			header('Location: http://'.$_SERVER['HTTP_HOST'].$_GET['_escaped_fragment_'].
			'?route=0');
			die();
		}
		$this->render('index');
	}
}

development/views/site/error.php
<?php
	$this->pageTitle = title("$code - ".httpError($code));
?>

<div class="raise"></div>
<div class="simple">There seems to be a <span><?php echo $code; ?> problem</span> here.</div>

development/views/site/index.php
<?php
	$this->pageTitle = title();
	$action = $this->action->id;
	if ($action == 'index') list($action, $data) = state('ajax');
	
	// debugging
	if (!user()->isGuest) {
		//$subject = 'Verify your account'; $type = 'verifyEmail';
		//sendMail($subject, $type, array('confirm'=>confirmCode($type)));
		//print_r(getimagesize('./uploads/r1rubl3s/example_ejl_print.png.png'));
		// 7 character for security token
		/*$key = encrypt('d50d5a3,68930413');
		echo substr($key, 0, 22);
		echo 'Decode: '.decrypt($key).', size: '.strlen($key);
		sendMail('Unauthorized email 2!', false, array('Email change stopped', 
		'Pirates be near, shiver me timbers!'));*/
		//1347818173 - substr(time(), 0, 6)
		/*$start = microtime(true);
		echo 'Time:'.((microtime(true) - $start)*1000).' ';*/
		/*echo encrypt(array('100095', '1', 'yonghui.yow@gmail.com'), false, true);
		print_r(decrypt('c596d73fREr6-JFXuZ6yxPfUwrE53w', false, true));
		print_r(decrypt('c596d734REr6-JFXuZ6yxPfUwrE53w', false, true));*/
		/*$file = File::model()->findByPk(100482);
		cs()->registerScript('test', JCrop::Script($file->path.'.png'));*/
		/*$action = 'job'; $data = 'listo-app-icon';
		cs()->registerScript('submit', "jQuery('#jcrop').attr('src', './uploads/r1rubl3s/test_2.png').".
		"attr('width', 582).attr('height', 534); ".
		"crop = $.Jcrop('#jcrop', {'allowSelect':false,'allowChange':false,".
		"'trueSize':[1166,1024],'setSelect':[72,1,1094,1023],'onChange':moveCoords,'onSelect':saveCoords}); ".
		"jQuery('.jcrop-holder').css('margin-top', 23); jQuery('#jcrop-thumb').attr('src', ".
		"'./uploads/r1rubl3s/test_2.png').attr('width', 163).attr('height', 143);");*/
		/*"jQuery('.jcrop-holder').css('margin-top', -40).css('margin-bottom', -40)"*/
	} else {
		//$this->widget('application.components.JuiWidget');
		/*$design = Design::model()->findByPk(1000044);
		$task = Task::model()->findByPk(100026);
		$desc = 'Check them out and grab your own beautiful icon.';
		$link = $this->createAbsoluteUrl('grid/'.hash_route(null, $task, 'task'));
		$uri = $this->createAbsoluteUrl('');
		$actions = json_encode(array('name'=>'Post Brief', 'link'=>$this->createAbsoluteUrl('/post')));
		$request = array('app_id'=>param('fbId'), 'display'=>'popup', 'link'=>$link, 'picture'=>'http://bidmygoods.com/test_round.png', 
		'name'=>'I bought a new handmade icon', 'caption'=>param('dscpt'), 'actions'=>$actions, 
		'description'=>$desc, 'redirect_uri'=>$uri, 'ref'=>'invoice');
		$share = 'https://www.facebook.com/dialog/feed?'.http_build_query($request, '', '&');
		$request = array('url'=>$link, 'text'=>$desc, 'via'=>$uri);
		$tweet = 'https://twitter.com/intent/tweet?'.http_build_query($request, '', '&');
		sendMail(array('report'=>'http://127.0.0.1/uber/report?entry=1ac9a8f7fACQ-Qj15TJZHSbCLtjaV'.
		'-hg1-_MRiAUSG9eRUVVCO5X-Bm8BIpbqPm7_Lgfk8vd2'), 'Email change notice', 'oldEmail', 100001);*/
	}
	
	$options = array('hidden'=>!in_array($action, array('index', 'category')));
	if (isset($class)) {
		$auth = $class == 'auth'; $this->pageTitle = $auth ? title($action) : title();
		echo openDiv('#system').closeDiv().($auth ? auth($action, $model) : openDiv('#approve').
		openDiv('.login').Plan::Model('Approve', Plot::Edit, new Mail)->html()).closeDiv().closeDiv();
	} else {
		if (user()->isGuest) {
			echo openDiv('#marketBar', $options);
			$count = Person::model()->count();
			?>
				<!--Get Custom Photos From Local Photographers-->
				<h1>Brief <?php echo $count; ?> Creative Professionals Instantly.</h1>
				<!--Receive Perfect Photos For Your Creative Projects-->
				<h2>Find The Perfect Creative For Your Business. Get Pitched Now.</h2>
				<div class="signup ocean"><?php echo CHtml::link("Let’s Get Started!", '#'); ?></div>
				<div class="claim">It is free to submit your brief!</div>
				<div class="divider"></div>
				<div id="howto">
					<h2>How It Works.</h2>
					<div class="unit">
						<img src="/images/invite.png" />
						<span>1. We Invite Curated Designers</span>
						<div class="signup"><a href="#">I’m A Creative</a></div>
					</div>
					<div class="unit">
						<img src="/images/pitch.png" />
						<span>2. You Receive Quality Samples</span>
						<!--<div id="signup" class="business"><a href="#">Try Now</a></div>-->
					</div>
					<div class="unit">
						<img src="/images/select.png" />
						<span>3. Select Favourite Creative</span>
					</div>
					<div class="unit">
						<img src="/images/receive.png" />
						<span>4. Receive Your Deliverables</span>
					</div>
				</div>
				<!--<div class="group">
					<h1>Redesign your App launcher icons</h1>
					<div class="sector"><div id="service" class="tree">
						<?php echo CHtml::link("I'm a designer", '#'); ?>
					</div></div>
					<h2>Your App Icon <span>Matters.</span></h2>
					<div id="post"><a href="<?php echo hash_route('', 'post'); ?>">
					Post Work</a></div>
				</div>
				<div class="group">
					<img src="/images/iphone_cover.png" />
				</div>-->
			<?php echo openDiv('.raise').closeDiv().closeDiv();
		} else if (verify() && !state('hide')) {
			$js = '$("a.resend").replaceWith("<strong>Email sent!</strong>")';
			$link = verify(1) ? EHtml::ajaxLink('#content', $js, array('class'=>'resend'), 
			app()->createUrl('site/resend'), '', array(), 'Send again!') : '';
			$type = user()->person->new_email ? 'new email' : 'email and receive proposals';
			echo openDiv('#verify').CHtml::openTag('span')."Please verify your $type by ".
			"clicking the link we sent you. $link".CHtml::closeTag('span').closeDiv();
			/*openDiv('#hide').CHtml::link('Hide', '#').closeDiv().*/
		}
		echo openDiv('#service', $options).CHtml::openTag('h1').'Choose A <span>Service</span> '.
		'and Submit Your <span>Project Brief</span>.'.CHtml::closeTag('h1').openDiv('.project');
		foreach (Category::model()->findAll() as $category) {
			list($name, $thumb) = intersect_model($category, array('name', 'thumb'));
			$route = hash_route('post'.'&type='.$category->row_id); $open = true;
			echo openDiv('.panel').($open ? CHtml::openTag('a', array('href'=>$route)) : 
			CHtml::image('/images/soon.png')).openDiv('.select', array('class'=>!$open ? 
			'soon' : false)).CHtml::image('/images/'.$thumb).closeDiv().($open ? 
			CHtml::closeTag('a') : '').openDiv('.note').$name.closeDiv().closeDiv();
		}
		echo closeDiv().openDiv('.raise').closeDiv().closeDiv();
		$agent = Agent::Browse; $hide = false; $page = $upload = '';
		if ($action == 'category') {
			$this->pageTitle = title(updateRefine($agent, $data, 'Category'));
		} else if ($action == 'post') {
			$page = Plan::Model('Task', Plot::Create, new Task)->html();
			$this->pageTitle = title('Post Brief'); $hide = true;
		} else if ($action == 'job') {
			$task = match_like('Task', $data);
			if ($task) {
				$page = Plan::Model('Task', Plot::View, $task)->html();
				$upload = Plan::Model('Upload', Plot::Edit, $task)->html();
				$this->pageTitle = title(state('upload') ? 'Submit your design' : $task->name);
			}
		} else if ($action == 'message') {
			$task = match_like('Task', $data[0]);
			$design = $task ? Design::model()->find('task_id=:tid AND mirror=:mirror', 
			array(':tid'=>$task->row_id, ':mirror'=>$data[1])) : false;
			if ($hide = $design) {
				$page = Plan::Model('Message', Plot::View, $design)->html();
				$this->pageTitle = 'Discussion on Submission #'.(int)$data[1];
			}
		} else if ($action == 'store') {
			$task = match_like('Task', $data);
			if ($hide = $task) {
				$page = Plan::Model('Grid', Plot::Edit, $task)->html();
				$upload = Plan::Model('Upload', Plot::Edit, $task)->html();
				$this->pageTitle = title(state('upload') ? 'Submit your design' : 
				'Submissions for '.$task->name);
			}
		} else if ($action == 'account' && !user()->isGuest) {
			$agent = Agent::Accounts;
			$this->pageTitle = title(Panel::Title($agent));
		} else if ($action == 'edit' && !user()->isGuest) {
			$page = openDiv('.profile').Plan::Model('Profile', Plot::Edit, 
			user()->person)->html().closeDiv();
			$this->pageTitle = title('Edit Profile');
		} else if ($action == 'profile') {
			if ($data !== null) {
				$person = match_like('person', $data);
				if ($person) {
					$page = openDiv('.profile').Plan::Model('Profile', Plot::View, 
					$person)->html().closeDiv();
					$this->pageTitle = title($person->name);
				}
			} else if (!user()->isGuest) {
				$agent = Agent::Profile;
				$this->pageTitle = title(Panel::Title($agent));
			}
		} else if ($action == 'space' && !user()->isGuest) {
			$agent = Agent::Space;
			$this->pageTitle = title(Panel::Title($agent));
		}
		$panel = Panel::Agent($agent);
		echo blockDiv('#page', $page == '' || state('upload')).$page.closeDiv();
		if (!user()->isGuest) echo blockDiv("#uploadBar", !state('upload')).$upload.closeDiv();
		echo $panel->display($page != '', isset($route), $hide || state('upload'));
		cs()->registerScript('setPanel', 'var panel = "'.$agent.'";', CClientScript::POS_END);
	}
	$load = openDiv('.load');
	foreach (array('arrow', 'back_orange', 'close', 'facebook', 'submit') as $file) {
		$load .= CHtml::image("/images/$file.png");
	}
	echo $load.closeDiv();