development/controllers/SiteController.php
<?php

class SiteController extends Controller
{
	/**
	 * Defines the access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow',
				'actions'=>array('edit', 'resend', 'message'),
				'users'=>array('@'),
			),
			array('allow',
				'actions'=>array('index', 'list', 'login', 'logout', 'page', 'register', 
					'session', 'validate', 'confirm', 'report', 'approve', 'error', 
					'category', 'job', 'person', 'post', 'store', 'stats7'),
				'users'=>array('*'),
			),
		);
	}
	
	protected function accessDenied($user, $message)
	{
		throw new CHttpException(403, $message);
	}
	
	/**
	 * Declares class-based actions
	 */
	public function actions()
	{
		return array(
			'page'=>array(
				'class'=>'CViewAction',
			),
		);
	}

	/**
	 * This is the action to handle external exceptions
	 */
	public function actionError($code=null)
	{
		$error = app()->errorHandler->error;
    	if (app()->request->isAjaxRequest) {
    		echo $error['message'];
    	} else {
    		if ($error) {
    			$code = $error['code'] != 404 ? $error['code'] : false;
    			$login = $code == 403 && user()->isGuest;
    			$url = ($login ? 'login' : 'error'.($code ? "/$code" : ''));
    			$this->redirect($this->createUrl($url));
    		}
			$this->render('error', array('code'=>$code ? $code : 404));
		}
	}
	
	/**
	 * Display tasks in list view
	 */
	public function actionList($agent, $order=false, $model=null, $set=null)
	{
		if (app()->request->isAjaxRequest) {
			if ($set === null) {
				if ($order) updateRefine($agent, $order, $model);
				if ($order && $model == 'Category') {
					state('ajax', array('category', $order));
				} else if ($agent != Agent::Browse) {
					if (!user()->isGuest) {
						$action = $agent == Agent::Accounts ? 'account' : ($agent 
						== Agent::Profile ? 'profile' : 'space');
						state('ajax', array($action, null));
					} else {
						$agent = Agent::Browse;
					}
				} else {
					state('ajax', array('index', null));
				}
				state('agent', $agent);
			} else {
				$refine = state('refine');
				$refine[$set] = $order;
				state('refine', $refine);
			}
			$this->widget('application.components.ListView', array(
				'agent'=>$agent,
			));
		}
	}

	/**
	 * Authorize email login
	 */
	public function actionLogin()
	{
		$model = personModel();
		if (isset($_POST['Person'])) {
			$model->attributes = $_POST['Person'];
			if ($model->login()) {
				$this->redirect(app()->homeUrl.'#!/');
			} else {
				$model->password = '';
			}
		}
		$this->render('index', array('class'=>'auth', 'model'=>$model));
	}
	
	/**
	 * Complete logout and redirect
	 */
	public function actionLogout()
	{
		user()->logout();
		if ($logout = facebook_api('logout')) {
			$this->redirect($logout);
		} else {
			$this->redirect(app()->homeUrl.'#!/');
		}
	}
	
	/**
	 * Process email registration
	 */
	public function actionRegister($member='customer')
	{
		$model = isset($_POST['Hub']) ? registerProfile($_POST['Hub'], 
		$member) : hubModel();
		$this->render('index', array('class'=>'auth', 'model'=>$model));
	}
	
	/**
	 * Updates the session variable data
	 */
	public function actionSession()
	{
		ignore_user_abort(1);
		foreach ($_GET as $key=>$val) {
			state($key, $val);
		}
	}
	
	/**
	 * Validate unique person
	 */
	public function actionValidate()
	{
		if (app()->request->isAjaxRequest && isset($_GET['Person'])) {
			foreach ($_GET['Person'] as $name=>$value) {
				if (!Person::model()->count($name.'=:val AND locked = 0', 
				array(':val'=>$value))) {
					echo CJavaScript::jsonEncode(false);
					return;
				}
			}
			echo CJavaScript::jsonEncode(true);
		}
	}
	
	/**
	 * Confirm email received
	 */
	public function actionConfirm($state, $code)
	{
		list($out, $person) = confirmCode($state, $code);
		if ($out) {
			if ($out == 'validChange' || $out == 'validEmail') {
				if ($out == 'validChange') {
					$person->email = $person->new_email;
					$person->new_email = null;
				}
				$person->valid_email = 1;
				$person->save();
			} else if ($out == 'validReset') {
				$refine = state('refine');
				foreach (multiRefine() as $i=>$multi) {
					if ($multi['panel'] == 'Accounts') {
						$refine[$i] = 'security';
					}
				}
				state('refine', $refine);
				$this->redirect(app()->createUrl('my/account'));
			}
			state('name', $person ? $person->first_name : '');
			$this->redirect(app()->createUrl("mail/$out"));
		}
		$this->redirect(app()->homeUrl);
	}
	
	/**
	 * Report from email
	 */
	public function actionReport($entry)
	{
		list($out, $email, $person) = reportCode($entry, true);
		if ($out == 'oldEmail') {
			$person->email = $email;
			$person->confirm_key = $person->new_email = null;
			$person->save();
		} else if ($out == 'newPassword') {
			$person->password = null;
			$person->save();
			// send password reset link
		}
		state('email', $email);
		state('name', $person ? $person->first_name : '');
		$this->redirect(app()->createUrl("mail/$out"));
	}
	
	/**
	 * Resend verification link
	 */
	public function actionResend()
	{
		if (app()->request->isAjaxRequest && verify(1)) {
			$subject = array('Activate this email', 'Verify your account');
			$type = array('newEmail', 'verifyEmail');
			$i = user()->person->new_email ? 0 : 1;
			queueMail(array('confirm'=>confirmCode($type[$i])), $subject[$i], $type[$i]);
		}
	}
	
	/**
	 * Redirect for users
	 */
	private function renderRoute($data, $route, $flush=true)
	{
		$action = $this->action->id;
		$focus = array('data'=>$data, 'route'=>$route);
		state('ajax', array($action, $data));
		if ($route) {
			$url = $this->createUrl('site/index')."#!/$action".($data ? "/$data" : '');
			if ($flush) {
				echo pageHeader().'<script type="text/javascript">document.title = "'.
				title('Please wait').'"; window.location = "'.$url.'"</script>';
				echo strstr($this->render('index', $focus, true), '<meta name');
			} else {
				$this->redirect($url);
			}
		} else {
			$this->render('index', $focus);
		}
	}
	
	/**
	 * View store page
	 */
	public function actionStore($name, $login=false, $route=true, 
	$paid=false, $token=null, $PayerID=null)
	{
		if ($paid && $token) {
			ignore_user_abort(1);
			// display a payment.php page "Payment processing..."
			$result = paypal_nvp('get', $token);
			if ($result && $result['PAYERID'] == $PayerID && paypal_nvp('make', $result)) {
				$task = Task::model()->findByPk($result['task_id']);
				$payment = new Payment;
				$payment->task_id = $task->row_id;
				$payment->person_id = $task->person_id;
				$payment->amount = $result['amount'];
				$payment->commit = 1;
				$payment->paid_on = new CDbExpression('NOW()'); 
				foreach ($result['designs'] as $mirror) {
					$design = Design::model()->find('task_id=:tid AND mirror=:mirror', 
					array(':tid'=>$task->row_id, ':mirror'=>$mirror));
					if (!$design->sold) {
						$design->sold = 1;
						$design->save();
						$payment = new Payment;
						$payment->task_id = $task->row_id;
						$payment->person_id = $design->person_id;
						$payment->amount = $task->price;
						$payment->debit = 0;
						$payment->fee = paypal_fee($task->price);
						$payment->save();
						$subject = "Purchase Invoice #$mirror";
						queueMail(array('design_id'=>$design->row_id, 
						'task_id'=>$task->row_id), $subject, 'invoice');
					}
				}
				$this->renderRoute($name, $route, false);
			} else {
				$this->redirect($this->createUrl('site/error', array('code'=>503)));
			}
		} else if (match_like('Task', $name)) {
			if ($login && user()->isGuest) {
				state('ajax', array('store', $name));
				$this->redirect($this->createUrl('site/login'));
			}
			$this->renderRoute($name, $route);
		} else {
			$this->missingAction('');
		}
	}
	
	/**
	 * View register confirmation
	 */
	public function actionApprove()
	{
		$this->render('index', array('class'=>'register'));
	}
	
	/**
	 * Browse category
	 */
	public function actionCategory($name, $route=true)
	{
		$this->renderRoute($name, $route);
	}
	
	/**
	 * View job page
	 */
	public function actionJob($name, $route=true)
	{
		if (match_like('Task', $name)) {
			$this->renderRoute($name, $route);
		} else {
			$this->missingAction('');
		}
	}
	
	/**
	 * View design message
	 */
	public function actionMessage($name, $order)
	{
		$task = match_like('Task', $name);
		$design = $task ? Design::model()->find('task_id=:tid AND mirror'.
		'=:mirror', array(':tid'=>$task->row_id, ':mirror'=>$order)) : false;
		state('ajax', array('message', array($name, $order)));
		if ($design && ($task->person_id == user()->id || $design->person_id == 
		user()->id)) {
			header('Location: '.$this->createAbsoluteUrl("#!/message/$name/$order"));
		} else {
			$this->missingAction('');
		}
	}
	
	/**
	 * View user profile
	 */
	public function actionPerson($alias, $route=true)
	{
		if (match_like('person', $alias)) {
			$this->renderRoute($alias, $route);
		} else {
			$this->missingAction('');
		}
	}
	
	/**
	 * Post job brief
	 */
	public function actionPost($route=true)
	{
		$this->renderRoute(null, $route);
	}
	
	/**
	 * Stats for protopage feed
	 */
	public function actionStats7()
	{
		echo '<div style="font-family: arial; font-size: 10pt; text-align: center">';
		$fields = array('Technetium'=>array(Payment::model(), 'debit=1'), 'Customers'=>
			array(Person::model(), 'member="customer"'), 'Designs'=>Design::model());
		foreach ($fields as $desc=>$model) {
			$list = is_array($model) ? $model[0]->findAll($model[1]) : $model->findAll();
			echo "<p>$desc: ".count($list).'</p>';
		}
		echo '</div>';
	}
	
	/**
	 * Default action
	 */
	public function actionIndex()
	{
		if (isset($_GET['_escaped_fragment_'])) {
			header("HTTP/1.1 301 Moved Permanently");
			header('Location: http://'.$_SERVER['HTTP_HOST'].$_GET['_escaped_fragment_'].
			'?route=0');
			die();
		}
		$this->render('index');
	}
}

development/views/site/pages/clients.php
<?php 
	$this->pageTitle = title('FAQ For Clients');
	$post = $this->createUrl('site/post');
	/*$apple = 'http://developer.apple.com/library/ios/documentation/iphone/conceptual/'.
	'iphoneosprogrammingguide/App-RelatedResources/App-RelatedResources.html';*/
?>

<h1>For Clients</h1>
<h2>1. Where can I get started?</h2>
<p><?php echo CHtml::link('Post a brief here.', $post); ?> It's free! We cater to a 
wide range of business design services.</p>

<h2>2. How much does it cost to post a brief?</h2>
<p>For this limited period, it is absolutely free to post a brief. Give it a try. 
<?php echo CHtml::link('Post a brief now!', $post); ?></p>

<h2>3. Can I keep my brief private?</h2>
<p>All project briefs are kept anonymous. Please take note that project briefs 
that display or identify the client will be revised before getting posted.</p>

<h2>4. What should I look out for in the pitches?</h2>
<p>Before accepting a pitch, you should make sure that you peruse them carefully in 
order to ensure that it meets your 1) project requirements, 2) time requirements, 3) 
revision requirements and 4) budget etc.</p>
<p>The deliverables schedule for your project should be pitched clearly in the pitches 
you receive. If a pitch satisfies you, simply accept it and kick-start your project!</p>

<h2>5. Do I need to pay a deposit when I accept a pitch?</h2>
<p>Yes, you will be required to pay a 25% deposit of the accepted quote to kick-start 
your project. You will however be invoiced for the full amount of the accepted quote 
when you accept a pitch.</p>

<h2>6. Are there any extra charges?</h2>
<p>No, there are no other fees outside of your accepted quote. The quote provided to 
you by a designer, if accepted by you, is the net price you will pay for the project.</p>

<h2>7. How do I give comments and feedback for a submitted design?</h2>
<p>You will be able to have a private conversation with your designer about the project 
and submitted work. You can offer up your feedback and request for changes.</p>
<p>Keep in mind that the pitch you accept should have details about revisions and 
timeline for delivery in accordance with your project brief.</p>

<h2>8. What files do I get as deliverables?</h2>
<p>In your brief, you can specify if you require a .psd file, or an ai. file as working 
files. We currently support these 2 file formats.</p>

<h2>9. What is the design transfer agreement?</h2>
<p>When you kick-start your project (when you select a pitch and make the deposit), you 
also agree acquire all the copyrights and IP to that design, from the designer for that 
project, contingent on the completion of the project, for the amount of the quote 
accepted by you.</p>

<h2>10. When do I pay for the project?</h2>
<p>You only pay for the balance of the project at the end of the project deadline set by 
you. Take care to set a reasonable project deadline for your budget, as this will affect 
the pitches you receive.</p>

<h2>11. What if I misplaced the digital files that I have purchased?</h2>
<p>We continue to store securely the submissions for your projects so should you 
misplace your project file(s), you can always download them again.</p>

<h2>12. What should I do if I suspect that a design has been misappropriated?</h2>
<p>You should contact us at <?php echo support(); ?> so we can investigate the matter. 
Please note that abuse of this reporting channel may get you suspended on Probaz.</p>

<h2>13. Why did my project brief not post?</h2>
<p>If we think your brief is not clear, we may contact you to furnish more details. 
This is to ensure that the designers know with clarity what your requirements are.</p>
<p>If you require help in writing a project brief, please contact us and we will help 
you construct a project brief. <?php echo support(1); ?></p>

<h2>14. How do I make an enquiry to Probaz?</h2>
<p><?php echo support(1); ?><br>We will reply you much sooner than 24 hours.</p>

<!--<h2>6. Can I put in my brief asking submissions to imitate another app say, Instagram’s 
app icon?</h2>
<p>No you may not do that. We ask that you be respectful of other Companies and their 
creative rights. We know you can be creative too! :) Please refer to our terms of use if 
you are not sure about certain rules on probaz.</p>

<h2>7. What are Apple’s guidelines for app icons?</h2>
<p>Apple crops and treats the designs that are submitted to it, including adding the reflective effects 
and cropping (You can choose not to have them: please consult your developer or designer on 
this). We make the effort to make designs submitted to you realistic so that you can make a 
better-informed choice on your purchases. For detailed information please refer to:
<?php /*echo Chtml::link($apple, $apple, array('target'=>'_blank'));*/ ?></p>

<h2>8. Do I have to buy a design that is submitted to me?</h2>
<p>No, if no design satisfies you, you have no obligation to purchase any. However soon, we 
will enable you to guarantee that you will buy a design when you create a brief in our next 
version. This will encourage more designers to be interested in your brief and you will thus 
naturally receive more designs.</p>

<h2>9. How do I buy and download the deliverables?</h2>
<p>You can purchase a design anytime even before the submission deadline ends. You have up 
to 7 days to purchase the designs after the submission deadline. The submission duration 
depends on the package that you select when you create your brief. <?php echo support(1); 
?></p>-->

development/views/site/pages/compiler.php
<?php
	if (host() == '127.0.0.1') {
		$path = Yii::getPathOfAlias('application.views.builds');
		$all = file_get_contents("$path/all.php"); $sep = "'";
		$base = new CController('base'); $base->layout = 'email';
		preg_match_all("/case $sep.+$sep/", $all, $matches);
		foreach ($matches[0] as $match) {
			$action = trim(strstr($match, $sep), $sep);
			list($base->action, $view) = explode('/', $action);
			$html = $base->render('//builds/all', array('action'=>$action), true);
			$web = "$path/$view.html";
			if (!file_exists($web) || $html != file_get_contents($web)) {
				$raw = $html;
				preg_match_all('/<a href="([^"]+)">([^<]+)<\/a>/', $html, $matches, 
				PREG_SET_ORDER | PREG_OFFSET_CAPTURE);
				$del = 0;
				foreach ($matches as $link) {
					$start = $link[0][1]-$del; $len = strlen($link[0][0]);
					$new = $link[2][0].': '.$link[1][0];
					$html = substr($html, 0, $start).$new.substr($html, $start+$len);
					$del += $len-strlen($new);
				}
				file_put_contents($web, $html);
				serverProc('webview', $path, array($view, 'html'));
				file_put_contents($web, $raw);
			}
		}
	}
	$this->redirect(app()->homeUrl);
?>

development/views/site/pages/designers.php
<?php 
	$this->pageTitle = title('FAQ for Designers');
	/*$apple = 'http://developer.apple.com/library/ios/documentation/iphone/conceptual/'.
	'iphoneosprogrammingguide/App-RelatedResources/App-RelatedResources.html';*/
?>

<h1>For Designers</h1>
<h2>1. Who should join Probaz – Professional Bazaar for design services?</h2>
<p>We are looking for the freelance creative professional, the 3-man design studio and 
the boutique agency to join us! If you fit the bill sign up here!</p>

<h2>2. Why should I use Probaz?</h2>
<p>Unlike other platforms, you do not submit final works until you are hired. We 
believe “no spec work” favors you, the designer.</p>
<p>Instead you submit .pdf pitches selling your or your business’s experience, CV, 
timeline for delivery (within the client’s requirements), vision for the project 
(including concept art, sketches etc) and quote for the project (within the client’s 
requirements) etc. You may include other relevant details that make you more attractive 
to the client. <?php echo CHtml::link('View a recommended pitch format', 
'/images/probaz.png'); ?>.</p>
<!--<p>If we receive any complains or disputes regarding originality of design work from 
clients over purchased work, we will investigate the matter. To prevent such hassle, 
please ensure that all submissions are original works. Further, ensure that you do not 
submit similar designs to different clients or to copy other submissions, or works from 
elsewhere.</p>-->

<h2>3. Why was my pitch removed?</h2>
<p>We reserve the right to remove pitches that are of unacceptable quality, or those that 
are deemed disrespectful to the client, any minority group, or children. If you feel that 
your pitch has been unfairly removed, please feel free to contact us at <?php 
echo support(); ?>.</p>

<h2>4. What if my pitch does not get chosen?</h2>
<p>Do not worry! There are other projects you can pitch to.</p>

<h2>5. When do I get paid for the project?</h2>
<p>You will be paid in full at the end of a project via Paypal, less Probaz’s fee, which 
is 25 percent. We will deposit the funds into your Paypal account within 7 working days 
of the end of the project.</p>
<p>We currently only do transfers via Paypal. You must update your Paypal information 
before you can submit a pitch. You may create a <?php echo CHtml::link(
'Paypal account here', 'https://www.paypal.com/sg/cgi-bin/webscr?cmd=_registration-run', 
array('target'=>'_blank')); ?> if you do not have one.</p>

<h2>6. What happens should (after) the client choose my pitch?</h2>
<p>Your account will then allow you to submit designs to the client’s account. You will 
then be able to collaborate, discuss details of the project and submissions, and submit 
revisions of the deliverables for the project.</p>

<h2>7. What is the Design Transfer Agreement?</h2>
<p>When you submit a working file, you are required to accept the Design Transfer 
Agreement (DTA). This agreement affirms that the IP rights to your, (or the entity you 
represent’s) submission is transferred to the client, contingent on the completion and 
payment of the project.</p>
<p>You also affirm that you (or the entity you represent) are the creator and owner of 
the design(s) you submit. We do not own the IP to any of your submitted designs, pitches, 
concepts and ideas at any point.</p>

<h2>8. What file formats should I use when I submit designs?</h2>
<p>The client may or may not specify the requirements for file formats for the 
deliverables so take care to follow the requirements of the project brief. However we 
currently only accept .psd files and .ai files.</p>

<h2>9. When does the project end?</h2>
<p>It ends at the time stipulated on the client’s project brief. He/she will make payment 
then, after which you will be paid within 7 days.</p>

<h2>10. I still have more questions. How do I make an enquiry?</h2>
<p><?php echo support(1); ?><br>We will reply you in lightning fast time.</p>

<!--<h2>10. What canvas sizes should I use in my submissions?</h2>
<p>To generate the relevant .png files, we require that you submit 1024 X 1024 .psd files. 
If you are designing in illustrator you do not need to worry about this however as a rule 
of thumb please submit works also of 1024 X 1024. Note that you need not round the edges 
of the artwork when submitting your designs. For detailed information about Apple’s 
regulations for the app store icons, please refer to: <?php /*echo Chtml::link($apple, $apple, 
array('target'=>'_blank'));*/ ?></p>-->

development/views/site/pages/expiredCode.php
<?php 
	$this->pageTitle = title('Expired Code');
	if (state_new('name')) $this->redirect(app()->createUrl('mail/wrongUrl'));
?>

<h2>Expired Code</h2>
<p>Sorry <?php echo state('name'); ?>, that code has already expired.</p>

development/views/site/pages/newPassword.php
<?php 
	$this->pageTitle = title('Undo Password Change');
?>

<h2>Unathorized Password Change</h2>
<p>Thanks <?php echo state('name'); ?>, this action has been reported. Your account 
has been locked and reset instructions sent to <?php echo state('email'); ?>.</p>

development/views/site/pages/oldEmail.php
<?php 
	$this->pageTitle = title('Undo Email Change');
?>

<h2>Unauthorized Email Change</h2>
<p>Thanks <?php echo state('name'); ?>, this action has been reported. Your account 
email has been reset to <?php echo state('email'); ?>.</p>

development/views/site/pages/privacy.php
<?php 
	$this->pageTitle = title('Privacy Policy');
?>

<h1>Privacy Policy</h1>
<h2>I. General Preliminaries</h2>
<p>This Privacy Policy governs the way in which probaz.com, a website fully owned and 
operated by UBERQUERY PTE. LTD., collects, uses and shares information gathered from 
users. The terms "we", "us", "our", the "company", “the website" refer to PROBAZ, and 
the terms "you", "your", a "user" refer to you: a user of probaz.com and our services.</p>
<p>By accessing probaz.com and/or using our services, you agree to the policies as laid 
out in this Privacy Policy, and consent to us collecting and using your information in 
certain ways detailed below. However we do not disclose your information to any 3rd 
parties except Google Analytics, unless required by law or explicitly consented by you. 
Please read this document IN FULL. If you do not agree with the Privacy Policy IN FULL, 
please send us your feedback, and we hope to see you back soon.</p>

<h2>II. Personal and Technical Information</h2>
<p>2.1 We gather voluntarily provided personal identification information from users when 
they register on the website, visit the website, submit a brief listing, upload a photo, 
make transactions, comment, or use any service or feature of the website. You can of 
course make changes and control your personal information on PROBAZ.</p>
<p>Information that users may be required to provide upon registration may include a 
username, email address, chosen password and in some cases, a company or business name. 
This information is only collected from users who provide them voluntarily at the point 
of registration or in subsequent time. Users are able to view and browse the website 
without registering, but will be unable to fully utilize the website’s features and the 
implicit services. You should also take care to update your personal information in case 
of any changes.</p>

<p>2.2 Some of this personal information may be available to fellow users of PROBAZ so 
that they can verify your identity and make necessary judgments regarding you.</p>
<p>2.3 We may gather technical information from users when they visit the Site. We employ 
the services of Google Analytics to collect certain technical information. Thus, the terms 
of use of this technical information are subject to Google Analytics' own Privacy Policy, 
and are not covered under our Privacy Policy. Please visit and read Google Analytics’ 
Privacy Policy at <?php echo ref_link('https://www.google.com/intl/en/analytics/privacy'.
'overview.html'); ?> for more information.</p>
<p>2.4 We may also collect information based on your viewing habits on PROBAZ using cookies, 
in order to keep a record of how many times the website is visited, for how long a period, 
and other related technical information. You can configure your browser to disable cookies 
or otherwise delete such cookies.</p>

<p>2.5 Other technical information include, but are not limited to, the type of browser 
used, the operating system of the users' computer, IP address, location, the device on 
which the website is accessed from, the referral URL and other similar information. This 
information is used to improve your experience on the website, for our internal analyses 
of data trends and may be used to improve our operations in order to better serve you.</p>
<p>2.6 We collect certain transactional information due to the nature of PROBAZ, such as 
Paypal information. We do not currently collect your credit card information.</p>
<p>2.7 Because of the nature of PROBAZ, digital files uploads are an essential part of our 
providing our service. Such digital files are stored securely and indefinitely. However we 
do not have any rights in the designs. All briefs that clients may post are also stored 
indefinitely. Your interactions with other users on PROBAZ are likewise, also stored 
indefinitely. Feedback, public and private communication between users on probaz.com is 
also stored in order to provide us with information to improve our services.</p>

<p>2.8 Should you opt to sign into PROBAZ using 3rd party platforms such as Facebook, we 
may have access to certain information that are provided by such 3rd party platforms.</p>
<p>2.9 PROBAZ is not to be used by persons under the age of 13. Therefore we will never 
intentionally collect any information from any persons under the age of 13. If you use 
PROBAZ while under the age of 13, you are violating our terms of use.</p>
<p>2.10 You may encounter links on PROBAZ via which you may access websites that are not 
under our purview and control. Doing so subjects you to that website’s policies and we are 
not responsible for your accessing a 3rd party website from probaz.com.</p>

<h2>III. Summary</h2>
<p>3.1 The Company takes our users' privacy very seriously. We do not sell or trade your 
personal information to any 3rd parties. Your personal information is only used in these 
ways:</p>
<ol type="i">
	<li>To personalize and enhance your experience on the website, such as to customize 
	displayed content;</li>
	<li>To protect our users and the Company in the event of any legal or financial 
	disputes;</li>
	<li>To conduct analyses anonymously. We may display personal information relevant to 
	your account, such as a profile photo, the number of briefs you have completed, or the 
	number of submissions you have made etc.;</li>
	<li>To enable other users to identify, verify and make judgments regarding you and 
	your submissions;</li>
	<li>To ensure that users that have been blacklisted do not manage to signup again;</li>
	<li>To communicate with you electronically;</li>
	<li>For accounting, billing purposes, internal business processes and regulatory 
	obligations but only to the necessary extent;</li>
	<li>To investigate complaints or issues pertaining to the policies governing PROBAZ.</li>
</ol>

<h2>IV. Is Your Information Secure?</h2>
<p>4.1 All information and files we collect and receive respectively, are stored on 3rd 
party servers. We take precautions to prevent unauthorized access, alteration and disclosure 
by third parties. However, any information transmitted through the Internet can never be 
fully secure, and while we make every effort to protect your information, you acknowledge 
that there are security and privacy risks on any website that are beyond our control, and 
that these risks are not completely eliminable. By using PROBAZ, you acknowledge that you 
are aware of such risks.</p>

<p>4.2 Your account on PROBAZ is protected by a password of your choosing of which even we 
do not possess. Thus you are responsible for the security of your account by protecting 
your password appropriately and ensuring that you have logged off from your account after 
accessing it. We encourage you to never give away your account passwords and login 
information to anyone else.</p>
<p>4.3 We do not sell or trade your personal information to 3rd parties. We also do not 
allow advertisers to collect data from you on our website.</p>

<h2>V. Changes To This Policy</h2>
<p>5.1 We reserve the right to amend this privacy policy from time to time as we grow. We 
will notify you about such changes via email or by issuing a notice on the website. By 
continuing to use the Site after the amendments, you acknowledge and agree that you are 
bound by any modifications to this Privacy Policy. Likewise, by not explicitly responding 
to any changes to this Privacy Policy, you indicate your awareness and consent to any such 
updates to this Privacy Policy.</p>

<h2>Contact Us</h2>
<p>Should you have any concerns and enquiries, please feel free to contact us at 
<?php echo support(); ?> and we will gladly attend to you.</p>
<p>This policy was last updated on the 19th of December 2012.</p>

development/views/site/pages/validChange.php
<?php 
	$this->pageTitle = title('Email Updated');
	if (state_new('name')) $this->redirect(app()->createUrl('mail/wrongUrl'));
?>

<h2>Email Updated</h2>
<p>Thanks <?php echo state('name'); ?>, your email was successfully updated.</p>
<!--Click here to <?php echo user()->isGuest ? 'login' : 'edit your profile'; ?>.-->

development/views/site/pages/validEmail.php
<?php
	$this->pageTitle = title('Email Verified');
	if (state_new('name')) $this->redirect(app()->createUrl('mail/wrongUrl'));
?>

<h2>Email Verified</h2>
<p>Thanks <?php echo state('name'); ?>, your email was successfully confirmed.</p>
<!--Click here to <?php echo user()->isGuest ? 'login' : 'edit your profile'; ?>.-->

development/views/site/pages/wrongUrl.php
<?php 
	$this->pageTitle = title('Wrong URL');
?>

<h2>Wrong URL</h2>
<p>Malformed email link was entered. Please copy/paste the URL fully.</p>